### ISSUE TITLE
Visual feedback when starting/stopping the addon

### ISSUE THREAD

**Issue by p2635** [TruongQToan/Automatically-flip-cards#5]
When the user does J or Shift+J, K or Shift+K the add on works well as it should.

It would be an improvement if the user is visually notified that the add-on is enabled/disabled.

For example: 'Automatically flip cards: now enabled', 'Automatically flip cards: now disabled'

**Comment by TruongQToan** [comment]
Thank you for all your feedback. I will try to add these features asap.
