### ISSUE TITLE
An add on you installed failed to load

### ISSUE THREAD

**Issue by JSY88** [TruongQToan/Automatically-flip-cards#6]
First of all, thank you for great things!
But it doesn't work for me(Windows 7, Anki 2.1.9).
How can I fix it?
![111](https://user-images.githubusercontent.com/47873412/53212158-3dfd3500-3687-11e9-9098-d4762927ba55.png)

**Comment by TruongQToan** [comment]
Thank you for your response. I have updated the response, you can update it now.

**Comment by JSY88** [comment]
> 당신의 응답을 주셔서 감사합니다. 응답을 업데이트했습니다. 지금 업데이트 할 수 있습니다.

Work perfectly!
Thank you!
